### ISSUE TITLE
disableTestGenerator breaks babel transpilation

### ISSUE THREAD

**Issue by gpoitch** [kellyselden/broccoli-jscs#31] opened 2015-05-07 01:01 UTC
When used in an ember-cli app, and I specify the option `disableTestGenerator: true`, babel transpilation no longer works.  I can put together a minimal reproduction repo if necessary. 

ember-cli 0.2.3
ember-cli-babel 5.0.0
broccoli-jscs 0.0.22

**Comment by kellyselden** [comment] 2015-05-07 14:29
I'll check this out this weekend.

**Comment by alexdiliberto** [comment] 2015-06-21 20:45
@gdub22 I was toying around with this issue and couldn't reproduce it, any chance you could provide a small repo to look at?

**Comment by gdub22** [comment] 2015-06-21 21:10
@alexdiliberto https://github.com/gdub22/jscs-babel-fail

While creating the minimal reproduction, it seems to break babel by simply adding broccoli-jscs at all.

**Comment by kellyselden** [comment] 2015-06-24 15:17
This is still on my radar. Gonna try and allocate some time to it.

**Comment by alexdiliberto** [comment] 2015-06-25 05:48
@kellyselden The issue starts here https://github.com/kellyselden/broccoli-jscs/commit/50f65586b622ab04dc082226fd94ce690ef14370. Am I missing something here? or is this simply an ember-cli issue like I believe it is

If an addon implements the `lintTree` hook by, lets say in some cases, conditionally returning back the original passed in `tree` argument from `lintTree(type, tree)` (as you can see here https://github.com/kellyselden/broccoli-jscs/commit/50f65586b622ab04dc082226fd94ce690ef14370), then the resulting merged tree within ember-cli's `.../lib/broccoli/ember-app.js` (https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L457) will break babel transpilation.

A known case is one that @gdub22 pointed out in his example reop, if you have ES6 formatted code within your ember app's `app.js` file. Now in this case, it will for some reason add a new module called `'<my-ember-app>/tests/app.js'`. This module will be added without proper babel transpilation. Note, this module isn't generated if `broccoli-jscs` is not a dependency of the project.

This is happening because we're simply returning back the passed in tree argument from `lintTree(type, tree)` as we don't need to pass back a `JSCSTree()` in this case where `disableTestGenerator=true`.

Anyways, whenever you get around to look let me know...interested to know more. Not sure if I explained that well.

**Comment by kellyselden** [comment] 2015-06-25 12:59
Thank you @alexdiliberto for your help. I found exactly what you are talking about, submitted an issue.

**Comment by opsb** [comment] 2015-09-26 22:48
Following

**Comment by kellyselden** [comment] 2015-09-30 00:43
Can anyone verify that this works on ember-cli master without any changes to broccoli-jscs? It seems to be working fine for me.

**Closed** 2021-07-19 21:14 UTC
